//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eChemSDL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChannelListJSON {
            get {
                return ((string)(this["ChannelListJSON"]));
            }
            set {
                this["ChannelListJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExperimentListJSON {
            get {
                return ((string)(this["ExperimentListJSON"]));
            }
            set {
                this["ExperimentListJSON"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double DefaultHighConc {
            get {
                return ((double)(this["DefaultHighConc"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SolvateColorsJSON {
            get {
                return ((string)(this["SolvateColorsJSON"]));
            }
            set {
                this["SolvateColorsJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LConcs {
            get {
                return ((string)(this["LConcs"]));
            }
            set {
                this["LConcs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileHistory {
            get {
                return ((string)(this["FileHistory"]));
            }
            set {
                this["FileHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastExp {
            get {
                return ((string)(this["LastExp"]));
            }
            set {
                this["LastExp"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""ChannelName"":""H2O"",""HighConc"":1.0,""PumpSpeed"":100,""ChannelColor"":""0, 210, 255"",""Address"":1,""TubeInnerDiameter"":3.0,""WheelDiameter"":35.0,""DivpermL"":19416},{""ChannelName"":""Ni(NO3)2"",""HighConc"":1.0,""PumpSpeed"":100,""ChannelColor"":""Green"",""Address"":2,""TubeInnerDiameter"":3.0,""WheelDiameter"":35.0,""DivpermL"":19416},{""ChannelName"":""Fe(NO3)3"",""HighConc"":0.5,""PumpSpeed"":100,""ChannelColor"":""255, 83, 0"",""Address"":3,""TubeInnerDiameter"":3.0,""WheelDiameter"":35.0,""DivpermL"":19416},{""ChannelName"":""Co(NO3)2"",""HighConc"":1.0,""PumpSpeed"":100,""ChannelColor"":""193, 0, 0"",""Address"":4,""TubeInnerDiameter"":3.0,""WheelDiameter"":35.0,""DivpermL"":19416},{""ChannelName"":""Na3Cit"",""HighConc"":1.0,""PumpSpeed"":100,""ChannelColor"":""191, 191, 0"",""Address"":255,""TubeInnerDiameter"":3.0,""WheelDiameter"":35.0,""DivpermL"":19416},{""ChannelName"":""NH4Cl"",""HighConc"":3.0,""PumpSpeed"":100,""ChannelColor"":""Black"",""Address"":255,""TubeInnerDiameter"":3.0,""WheelDiameter"":35.0,""DivpermL"":19416},{""ChannelName"":""KOH"",""HighConc"":10.0,""PumpSpeed"":100,""ChannelColor"":""128, 0, 255"",""Address"":255,""TubeInnerDiameter"":3.0,""WheelDiameter"":35.0,""DivpermL"":19416},{""ChannelName"":""HNO3"",""HighConc"":5.0,""PumpSpeed"":100,""ChannelColor"":""255, 0, 128"",""Address"":255,""TubeInnerDiameter"":3.0,""WheelDiameter"":35.0,""DivpermL"":19416}]")]
        public string DefaultChannels {
            get {
                return ((string)(this["DefaultChannels"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double TotalVol {
            get {
                return ((double)(this["TotalVol"]));
            }
            set {
                this["TotalVol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlushingPumpsJSON {
            get {
                return ((string)(this["FlushingPumpsJSON"]));
            }
            set {
                this["FlushingPumpsJSON"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public ushort DefaultFlusherRPM {
            get {
                return ((ushort)(this["DefaultFlusherRPM"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Flusher485Port {
            get {
                return ((string)(this["Flusher485Port"]));
            }
            set {
                this["Flusher485Port"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DefaultFlusherDuration {
            get {
                return ((int)(this["DefaultFlusherDuration"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataFilePath {
            get {
                return ((string)(this["DataFilePath"]));
            }
            set {
                this["DataFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zh")]
        public string Culture {
            get {
                return ((string)(this["Culture"]));
            }
            set {
                this["Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PositionerJSON {
            get {
                return ((string)(this["PositionerJSON"]));
            }
            set {
                this["PositionerJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StopOnPanic {
            get {
                return ((bool)(this["StopOnPanic"]));
            }
            set {
                this["StopOnPanic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RS485Port {
            get {
                return ((string)(this["RS485Port"]));
            }
            set {
                this["RS485Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double DefaultTubeDiameter {
            get {
                return ((double)(this["DefaultTubeDiameter"]));
            }
            set {
                this["DefaultTubeDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DefaultMotorSpeed {
            get {
                return ((int)(this["DefaultMotorSpeed"]));
            }
            set {
                this["DefaultMotorSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultMotorClockwise {
            get {
                return ((bool)(this["DefaultMotorClockwise"]));
            }
            set {
                this["DefaultMotorClockwise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double DefaultWheelDiameter {
            get {
                return ((double)(this["DefaultWheelDiameter"]));
            }
            set {
                this["DefaultWheelDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19416")]
        public ushort DefaultDivPerML {
            get {
                return ((ushort)(this["DefaultDivPerML"]));
            }
            set {
                this["DefaultDivPerML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""PumpName"":""Inlet"",""Address"":5,""PumpRPM"":100,""Direction"":1,""PumpStatus"":{""IsRunning"":false,""LastSeen"":""2025-07-03T10:34:29.2613126+08:00"",""LastResponse"":""+wHxAe4=""},""CycleDuration"":30},{""PumpName"":""Outlet"",""Address"":6,""PumpRPM"":100,""Direction"":1,""PumpStatus"":{""IsRunning"":false,""LastSeen"":""2025-07-03T10:34:29.6437938+08:00"",""LastResponse"":""+wLxAe8=""},""CycleDuration"":30},{""PumpName"":""Transfer"",""Address"":7,""PumpRPM"":100,""Direction"":1,""PumpStatus"":{""IsRunning"":false,""LastSeen"":""0001-01-01T00:00:00"",""LastResponse"":null},""CycleDuration"":30}]")]
        public string DefaultFlushingPumps {
            get {
                return ((string)(this["DefaultFlushingPumps"]));
            }
            set {
                this["DefaultFlushingPumps"] = value;
            }
        }
    }
}
