//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eChemSDL {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eChemSDL.UserStrings", typeof(UserStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动灵敏度 (仅在扫速低于10 mV/s时有效) 的本地化字符串。
        /// </summary>
        internal static string AutoSens {
            get {
                return ResourceManager.GetString("AutoSens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先复位程序或在编辑器里保存修改，再列出参数。 的本地化字符串。
        /// </summary>
        internal static string BeforeListParam {
            get {
                return ResourceManager.GetString("BeforeListParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空白 的本地化字符串。
        /// </summary>
        internal static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验正在运行中，不能跳转！ 的本地化字符串。
        /// </summary>
        internal static string CannotJump {
            get {
                return ResourceManager.GetString("CannotJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很遗憾，这个溶液配不出来。。。 的本地化字符串。
        /// </summary>
        internal static string CannotMakeSol {
            get {
                return ResourceManager.GetString("CannotMakeSol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定运行单次实验吗？ 的本地化字符串。
        /// </summary>
        internal static string CFMRun {
            get {
                return ResourceManager.GetString("CFMRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定运行组合实验吗？ 的本地化字符串。
        /// </summary>
        internal static string CFMRunCombo {
            get {
                return ResourceManager.GetString("CFMRunCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定中止实验吗？ 的本地化字符串。
        /// </summary>
        internal static string CFMStop {
            get {
                return ResourceManager.GetString("CFMStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 换样 的本地化字符串。
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于所指定冲洗时间过短，无法完成一次循环；现已自动将其设置为一次循环的时间。 的本地化字符串。
        /// </summary>
        internal static string ChangeFlushCycle {
            get {
                return ResourceManager.GetString("ChangeFlushCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道 的本地化字符串。
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合实验数目 的本地化字符串。
        /// </summary>
        internal static string CmbExpCnt {
            get {
                return ResourceManager.GetString("CmbExpCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合 的本地化字符串。
        /// </summary>
        internal static string ComboExp {
            get {
                return ResourceManager.GetString("ComboExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合实验进程 的本地化字符串。
        /// </summary>
        internal static string ComboExpProgress {
            get {
                return ResourceManager.GetString("ComboExpProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合实验参数未初始化，请先运行组合实验编辑器。 的本地化字符串。
        /// </summary>
        internal static string ComboNotValid {
            get {
                return ResourceManager.GetString("ComboNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浓度 的本地化字符串。
        /// </summary>
        internal static string Conc {
            get {
                return ResourceManager.GetString("Conc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限制总浓度恒定后的实验数目为： 的本地化字符串。
        /// </summary>
        internal static string ConstConCmbExpCnt {
            get {
                return ResourceManager.GetString("ConstConCmbExpCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前 的本地化字符串。
        /// </summary>
        internal static string CurrentExp {
            get {
                return ResourceManager.GetString("CurrentExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前步骤 的本地化字符串。
        /// </summary>
        internal static string CurrentStep {
            get {
                return ResourceManager.GetString("CurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定制 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向 的本地化字符串。
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持续时间 的本地化字符串。
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持续 (秒) 的本地化字符串。
        /// </summary>
        internal static string DurationSec {
            get {
                return ResourceManager.GetString("DurationSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始电位 (V) 的本地化字符串。
        /// </summary>
        internal static string E0 {
            get {
                return ResourceManager.GetString("E0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验数据已保存。 的本地化字符串。
        /// </summary>
        internal static string ECDataSaved {
            get {
                return ResourceManager.GetString("ECDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电化学 的本地化字符串。
        /// </summary>
        internal static string EChem {
            get {
                return ResourceManager.GetString("EChem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电化学实验参数 的本地化字符串。
        /// </summary>
        internal static string ECParams {
            get {
                return ResourceManager.GetString("ECParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电化学工作站 的本地化字符串。
        /// </summary>
        internal static string ECStation {
            get {
                return ResourceManager.GetString("ECStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止电位 (V) 的本地化字符串。
        /// </summary>
        internal static string EF {
            get {
                return ResourceManager.GetString("EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上限电位 (V) 的本地化字符串。
        /// </summary>
        internal static string EH {
            get {
                return ResourceManager.GetString("EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下限电位 (V) 的本地化字符串。
        /// </summary>
        internal static string EL {
            get {
                return ResourceManager.GetString("EL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电解液 的本地化字符串。
        /// </summary>
        internal static string Electrolyte {
            get {
                return ResourceManager.GetString("Electrolyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅排空溶液，不注水冲洗。 的本地化字符串。
        /// </summary>
        internal static string EvacOnly {
            get {
                return ResourceManager.GetString("EvacOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终值 的本地化字符串。
        /// </summary>
        internal static string FinalValue {
            get {
                return ResourceManager.GetString("FinalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲洗 的本地化字符串。
        /// </summary>
        internal static string Flush {
            get {
                return ResourceManager.GetString("Flush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲洗泵失去响应。 的本地化字符串。
        /// </summary>
        internal static string FlushPumpComError {
            get {
                return ResourceManager.GetString("FlushPumpComError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正转 的本地化字符串。
        /// </summary>
        internal static string forward {
            get {
                return ResourceManager.GetString("forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备忙！ 的本地化字符串。
        /// </summary>
        internal static string HWBusy {
            get {
                return ResourceManager.GetString("HWBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闲置 的本地化字符串。
        /// </summary>
        internal static string idle {
            get {
                return ResourceManager.GetString("idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法指令！ 的本地化字符串。
        /// </summary>
        internal static string IllegalCommand {
            get {
                return ResourceManager.GetString("IllegalCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以上勾选计入总浓度 的本地化字符串。
        /// </summary>
        internal static string IncludeInTotalConc {
            get {
                return ResourceManager.GetString("IncludeInTotalConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初值 的本地化字符串。
        /// </summary>
        internal static string InitialValue {
            get {
                return ResourceManager.GetString("InitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注液顺序 的本地化字符串。
        /// </summary>
        internal static string InjectOrder {
            get {
                return ResourceManager.GetString("InjectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进液 的本地化字符串。
        /// </summary>
        internal static string Inlet {
            get {
                return ResourceManager.GetString("Inlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔 的本地化字符串。
        /// </summary>
        internal static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是溶剂 的本地化字符串。
        /// </summary>
        internal static string IsSolvent {
            get {
                return ResourceManager.GetString("IsSolvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳到实验 的本地化字符串。
        /// </summary>
        internal static string JumptoExp {
            get {
                return ResourceManager.GetString("JumptoExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标浓度 (/L): 的本地化字符串。
        /// </summary>
        internal static string LowConc {
            get {
                return ResourceManager.GetString("LowConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大转速 的本地化字符串。
        /// </summary>
        internal static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电机地址 的本地化字符串。
        /// </summary>
        internal static string MotorAd {
            get {
                return ResourceManager.GetString("MotorAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电机状态 的本地化字符串。
        /// </summary>
        internal static string MotorState {
            get {
                return ResourceManager.GetString("MotorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负扫 的本地化字符串。
        /// </summary>
        internal static string NegScan {
            get {
                return ResourceManager.GetString("NegScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先建立一个基础实验程序。 的本地化字符串。
        /// </summary>
        internal static string NoBaseExp {
            get {
                return ResourceManager.GetString("NoBaseExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有连接，请检查。 的本地化字符串。
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有实验，请新建或者载入一个实验。 的本地化字符串。
        /// </summary>
        internal static string NoExpDefined {
            get {
                return ResourceManager.GetString("NoExpDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作类型 的本地化字符串。
        /// </summary>
        internal static string OperType {
            get {
                return ResourceManager.GetString("OperType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排液 的本地化字符串。
        /// </summary>
        internal static string Outlet {
            get {
                return ResourceManager.GetString("Outlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超出范围 的本地化字符串。
        /// </summary>
        internal static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入数值超出范围! 的本地化字符串。
        /// </summary>
        internal static string OutOfRangeLong {
            get {
                return ResourceManager.GetString("OutOfRangeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变量 的本地化字符串。
        /// </summary>
        internal static string Param {
            get {
                return ResourceManager.GetString("Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数的个数不匹配！ 的本地化字符串。
        /// </summary>
        internal static string ParamCountError {
            get {
                return ResourceManager.GetString("ParamCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取放 的本地化字符串。
        /// </summary>
        internal static string PickandPlace {
            get {
                return ResourceManager.GetString("PickandPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口可能被强制占用，请重启程序或者改变端口。 的本地化字符串。
        /// </summary>
        internal static string PortOccupied {
            get {
                return ResourceManager.GetString("PortOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样品平台 的本地化字符串。
        /// </summary>
        internal static string Positioner {
            get {
                return ResourceManager.GetString("Positioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正扫 的本地化字符串。
        /// </summary>
        internal static string PosScan {
            get {
                return ResourceManager.GetString("PosScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配液 的本地化字符串。
        /// </summary>
        internal static string PrepSol {
            get {
                return ResourceManager.GetString("PrepSol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速推拉针筒除气泡，活塞应先退后以防碰撞。 的本地化字符串。
        /// </summary>
        internal static string PrimeDesc {
            get {
                return ResourceManager.GetString("PrimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改已保存，是否关闭编辑器？ 的本地化字符串。
        /// </summary>
        internal static string ProgramSavedandClose {
            get {
                return ResourceManager.GetString("ProgramSavedandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泵地址 的本地化字符串。
        /// </summary>
        internal static string PumpAddress {
            get {
                return ResourceManager.GetString("PumpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静置时间 (秒) 的本地化字符串。
        /// </summary>
        internal static string QuietTime {
            get {
                return ResourceManager.GetString("QuietTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收 的本地化字符串。
        /// </summary>
        internal static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备返回数据长度（字节）： 的本地化字符串。
        /// </summary>
        internal static string ReturnBytes {
            get {
                return ResourceManager.GetString("ReturnBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反转 的本地化字符串。
        /// </summary>
        internal static string reverse {
            get {
                return ResourceManager.GetString("reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行时间 (秒) 的本地化字符串。
        /// </summary>
        internal static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录间隔 的本地化字符串。
        /// </summary>
        internal static string SamplingInterval {
            get {
                return ResourceManager.GetString("SamplingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果指定总浓度，保存修改以计算实际实验数目。 的本地化字符串。
        /// </summary>
        internal static string SaveToCalCnt {
            get {
                return ResourceManager.GetString("SaveToCalCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描方向 的本地化字符串。
        /// </summary>
        internal static string ScanDir {
            get {
                return ResourceManager.GetString("ScanDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫速 (V/s) 的本地化字符串。
        /// </summary>
        internal static string ScanRate {
            get {
                return ResourceManager.GetString("ScanRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描段数 的本地化字符串。
        /// </summary>
        internal static string SegNum {
            get {
                return ResourceManager.GetString("SegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灵敏度 的本地化字符串。
        /// </summary>
        internal static string Sensitivity {
            get {
                return ResourceManager.GetString("Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定转速 的本地化字符串。
        /// </summary>
        internal static string SetSpeed {
            get {
                return ResourceManager.GetString("SetSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置已保存，是否关闭对话框？ 的本地化字符串。
        /// </summary>
        internal static string SettingsSavedandClose {
            get {
                return ResourceManager.GetString("SettingsSavedandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟实验（随机数据）开始。 的本地化字符串。
        /// </summary>
        internal static string SimExp {
            get {
                return ResourceManager.GetString("SimExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简单 的本地化字符串。
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 溶液 的本地化字符串。
        /// </summary>
        internal static string Sol {
            get {
                return ResourceManager.GetString("Sol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 溶液配方 的本地化字符串。
        /// </summary>
        internal static string SolRcp {
            get {
                return ResourceManager.GetString("SolRcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 溶剂 的本地化字符串。
        /// </summary>
        internal static string Solvent {
            get {
                return ResourceManager.GetString("Solvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源 的本地化字符串。
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止记录 的本地化字符串。
        /// </summary>
        internal static string StopLogging {
            get {
                return ResourceManager.GetString("StopLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现【错误】时停止执行程序。 的本地化字符串。
        /// </summary>
        internal static string StopOnError {
            get {
                return ResourceManager.GetString("StopOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方式 的本地化字符串。
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法 的本地化字符串。
        /// </summary>
        internal static string Technique {
            get {
                return ResourceManager.GetString("Technique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行时间 的本地化字符串。
        /// </summary>
        internal static string TimeProgress {
            get {
                return ResourceManager.GetString("TimeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总体积 (mL): 的本地化字符串。
        /// </summary>
        internal static string TotalVol {
            get {
                return ResourceManager.GetString("TotalVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移液 的本地化字符串。
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双向 的本地化字符串。
        /// </summary>
        internal static string two_way {
            get {
                return ResourceManager.GetString("two_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式错误 的本地化字符串。
        /// </summary>
        internal static string WrongFormat {
            get {
                return ResourceManager.GetString("WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的容量数值 (不含单位mL)! 的本地化字符串。
        /// </summary>
        internal static string WrongVolFormat {
            get {
                return ResourceManager.GetString("WrongVolFormat", resourceCulture);
            }
        }
    }
}
